version: '3'

services:
  elder_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: gestao
      POSTGRES_PASSWORD: gestao
      POSTGRES_DB: gestao
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
